import { Contact } from '../types';

export const DEFAULT_CONTACTS: Contact[] = [
  {
    id: 'cnt-01',
    genre: 'M.',
    firstName: 'Martin',
    lastName: 'ONILLON',
    escale: 'TLS',
    entity: 'HUBJOB',
    company: 'Hubjob Toulouse',
    service: 'Direction & Opérations',
    position: 'Responsable d\'agence',
    mobilePhone: '06 12 34 56 78',
    landlinePhone: '05 61 00 12 34',
    email: 'martin.onillon@hubjob.fr',
    comment: 'Contact principal HUBJOB Occitanie.',
    createdAt: '2026-01-15T09:00:00.000Z'
  },
  {
    id: 'cnt-02',
    genre: 'Mme',
    firstName: 'Claire',
    lastName: 'DUBOIS',
    escale: 'MRS',
    entity: 'ALYZIA',
    company: 'Alyzia Aéroport Marseille',
    service: 'Ressources Humaines',
    position: 'Coordinatrice RH & Formation',
    mobilePhone: '06 98 76 54 32',
    landlinePhone: '04 42 00 55 66',
    email: 'claire.dubois@alyzia.com',
    comment: 'Gestion des plannings piste et passage Marseille.',
    createdAt: '2026-01-18T10:30:00.000Z'
  },
  {
    id: 'cnt-03',
    genre: 'M.',
    firstName: 'Alexandre',
    lastName: 'MOREAU',
    escale: 'LYS',
    entity: "GIMN'S",
    company: "Gimn's Lyon",
    service: 'Exploitation Piste',
    position: 'Superviseur Avion',
    mobilePhone: '07 88 11 22 33',
    landlinePhone: '04 72 10 99 88',
    email: 'alexandre.moreau@gimns.com',
    comment: 'Astreinte week-end et coordination trafic.',
    createdAt: '2026-02-01T14:15:00.000Z'
  },
  {
    id: 'cnt-04',
    genre: 'Mme',
    firstName: 'Sophie',
    lastName: 'LAMBERT',
    escale: 'NCE',
    entity: 'ALYZIA',
    company: 'Alyzia Nice Côte d\'Azur',
    service: 'Passage',
    position: 'Chef d\'escale adjointe',
    mobilePhone: '06 44 55 66 77',
    landlinePhone: '04 93 21 00 11',
    email: 'sophie.lambert@alyzia.com',
    comment: 'Interlocutrice litiges bagages et service VIP.',
    createdAt: '2026-02-05T11:00:00.000Z'
  },
  {
    id: 'cnt-05',
    genre: 'M.',
    firstName: 'Julien',
    lastName: 'BERNARD',
    escale: 'BOD',
    entity: 'GIMAS',
    company: 'Gimas Bordeaux Mérignac',
    service: 'Assistance en Escale',
    position: 'Responsable Opérations Sol',
    mobilePhone: '06 22 33 44 55',
    landlinePhone: '05 56 12 34 56',
    email: 'julien.bernard@gimas.aero',
    comment: 'Référent sécurité piste et matériel GSE.',
    createdAt: '2026-02-10T16:45:00.000Z'
  },
  {
    id: 'cnt-06',
    genre: 'Mme',
    firstName: 'Élodie',
    lastName: 'GARCIA',
    escale: 'NTE',
    entity: 'HUBJOB',
    company: 'Hubjob Nantes',
    service: 'Recrutement Intérim',
    position: 'Chargée de recrutement',
    mobilePhone: '07 60 70 80 90',
    landlinePhone: '02 40 89 12 34',
    email: 'elodie.garcia@hubjob.fr',
    comment: 'Dossiers RH, habilitations et contrats aéroportuaires.',
    createdAt: '2026-02-14T08:30:00.000Z'
  },
  {
    id: 'cnt-07',
    genre: 'M.',
    firstName: 'Thomas',
    lastName: 'ROUSSEL',
    escale: 'GROUPE',
    entity: 'FORMATION',
    company: 'HubStation Academy',
    service: 'Pôle Formation & Qualité',
    position: 'Formateur Référent Réglementaire',
    mobilePhone: '06 11 22 33 44',
    landlinePhone: '01 48 00 11 22',
    email: 'thomas.roussel@formation.hubjob.fr',
    comment: 'Sessions 11.2.6.2, 11.2.3.8 et CACES.',
    createdAt: '2026-02-20T09:15:00.000Z'
  },
  {
    id: 'cnt-08',
    genre: 'M.',
    firstName: 'David',
    lastName: 'LECLERC',
    escale: 'HBO',
    entity: 'HBO',
    company: 'Hubjob Back Office',
    service: 'Administration des Ventes & Paie',
    position: 'Gestionnaire Paie & Facturation',
    mobilePhone: '06 77 88 99 00',
    landlinePhone: '01 49 80 70 60',
    email: 'david.leclerc@hubjob.fr',
    comment: 'Validation imports HBO, facturation client et acomptes.',
    createdAt: '2026-03-01T10:00:00.000Z'
  },
  {
    id: 'cnt-09',
    genre: 'Mme',
    firstName: 'Camille',
    lastName: 'FAURE',
    escale: 'MPL',
    entity: 'AHP',
    company: 'AHP Montpellier Méditerranée',
    service: 'Trafic & Dispatch',
    position: 'Agent de trafic principal',
    mobilePhone: '06 33 22 11 00',
    landlinePhone: '04 67 20 88 77',
    email: 'camille.faure@ahp-assistance.fr',
    comment: 'Plans de chargement et centrage.',
    createdAt: '2026-03-05T15:20:00.000Z'
  },
  {
    id: 'cnt-10',
    genre: 'M.',
    firstName: 'Laurent',
    lastName: 'PETIT',
    escale: 'BES',
    entity: 'CAPRES',
    company: 'Capres Brest Bretagne',
    service: 'Maintenance Sol',
    position: 'Responsable Technique',
    mobilePhone: '07 50 40 30 20',
    landlinePhone: '02 98 32 00 12',
    email: 'laurent.petit@capres.fr',
    comment: 'Entretien des engins et passerelles.',
    createdAt: '2026-03-10T13:40:00.000Z'
  }
];
